### ISSUE TITLE
Open Source Checklist

### ISSUE THREAD

**Issue by csholmes** [Shopify/salesforce_chunker#34]
Things to do before open sourcing `salesforce_chunker`

- [x] Bug fix/ naming: "query" vs "payload" vs "data" for batches. (https://github.com/Shopify/salesforce_chunker/pull/35)
- [x] Agree on naming conventions ("Entity"? "SObject"? "Query"? "SOQL"?) (https://github.com/Shopify/salesforce_chunker/pull/39)
- [x] Better logging (https://github.com/Shopify/salesforce_chunker/pull/38)
- [x] Delete stale branches
- [x] Fix Upsert Bug (https://github.com/Shopify/salesforce_chunker/pull/41)
- [x] Strengthen README (https://github.com/Shopify/salesforce_chunker/pull/42)
- ~Implement `wait_until_results_completed`~ this can wait
- [x] https://github.com/Shopify/salesforce_chunker/pull/43
- [x] Convert all parameters to hash-type parameters (https://github.com/Shopify/salesforce_chunker/pull/33, https://github.com/Shopify/salesforce_chunker/pull/40)
- [x] Update version to 1.x.x (https://github.com/Shopify/salesforce_chunker/pull/36, https://github.com/Shopify/salesforce_chunker/pull/40)
